# Generated by Django 5.0.6 on 2024-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_blog_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
